version: '3.9'

services:
  app:
    build:
      context: ./DatabaseAssistance
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - DatabaseAssistance/.env
    depends_on:
      - db
    volumes:
      - ./DatabaseAssistance:/app
      - ./DatabaseAssistance:/app/scripts
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: planmans
      POSTGRES_USER: planmans
      POSTGRES_PASSWORD: Ls4LEZ#c!u
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge